### ISSUE TITLE
VRCFury update protected object

### ISSUE THREAD

**Issue by ArcaneFoxie** [wholesomevr/SPS-Configurator#3]
in the latest versions of VRCFury (1.1114.0) it seams transform from the class VFGameObject has been made private causing compilation to fail

Workaround: Downgrade VRCFury (1.1112.0)

![Unity_jWfxvyDUXJ](https://github.com/user-attachments/assets/b8418026-de34-4c67-b8e2-4aa43acac6ad)

![image](https://github.com/user-attachments/assets/d326cb9a-ffbf-46b1-a42e-ebaa848bf275)

**Comment by wholesomevr** [comment]
Thank you for reporting the issue.
https://github.com/wholesomevr/SPS-Configurator/commit/3dff09c618dcc9f433482a6009f7f8022c64f7de fixes it.
https://github.com/VRCFury/VRCFury/pull/318 needs to be merged before I can make a new release.
In the meantime VRCFury added a workaround https://github.com/VRCFury/VRCFury/commit/4b98ed87a8d3a0cb58c3d74eef03b31ed4ce4e5c
